### ISSUE TITLE
【Web 支持】能否实现浏览器版本？

### ISSUE THREAD

**Issue by KonghaYao** [NightFurySL2001/CJK-character-count#20]
技术上来说，我觉得可以实现在线版本，中文网字计划借鉴了您的项目实现了网络上查看字体的适配情况。
通过 harfbuzz 或者 opentype.js 抽取字体文件中的 unicode 值，然后匹配字符数据库能够得到近似的效果。
如果是生成 APP 的话，electron 或者 tarui 都可以支持跨平台的 APP，稳定性也比较好。

<img width="919" alt="image" src="https://github.com/NightFurySL2001/CJK-character-count/assets/68177907/d8acbbe9-0127-4bb2-9b2d-0b2ede55d126">

**Comment by NightFurySL2001** [comment]
理论上当然可以实现，但是主要有几个原因：
1. HTML/CSS/JavaScript 我还是不太熟悉啊，效果成品不会比现在好。
2. 用 electron/tarui 需要打包额外的浏览器来渲染
3. 如果另外分开做网页版，需要同时维护两个codebase有点麻烦

目前的计划是继续用 Python，UI 改用 KivyMD 修缮用户界面。

**Comment by KonghaYao** [comment]
嗯，理解理解。我想可以将数据文件和 GUI 分开管理，因为现在仓库里面的数据文件全部放在根目录了，希望能够放置到 data 目录，这样开发者比较好查看源码。
如果可以的话，我们的项目会通过 npm 直接引用 GITHUB 仓库的同一份数据文件去进行一些操作。

**Comment by NightFurySL2001** [comment]
如果是要单纯的字表数据，可以参考这个repo： https://github.com/NightFurySL2001/cjktables ，里面的数据更详细。
