### ISSUE TITLE
字体重复。

### ISSUE THREAD

**Issue by Ablank1995** [NightFurySL2001/CJK-character-count#22]
665A是晚  664A是晊 
现在输入晚字出来的是晊。

6743是权  6741是杁  673E是朾
字体很不错，希望能改一下。

![Snipaste_2024-03-13_20-16-52](https://github.com/NightFurySL2001/CJK-character-count/assets/157212795/b317eb8a-4784-4e6d-9b64-e93f0dade0c5)
![3个](https://github.com/NightFurySL2001/CJK-character-count/assets/157212795/51090e83-8742-4162-afde-df0756001a58)
![Snipaste_2024-03-13_20-25-37](https://github.com/NightFurySL2001/CJK-character-count/assets/157212795/82cac32c-e522-481b-8a11-494ee5303baa)

**Comment by NightFurySL2001** [comment]
您好，您的截图是「**[字帮玩酷体](https://www.maoken.com/freefonts/17666.html)**」。本仓库是字体计数软件，只是提供计算汉字数量给猫啃网使用而已。请你前往该字体作者的页面提报 https://www.zcool.com.cn/work/ZNjM2NjMxNTY=.html 。谢谢。
