### ISSUE TITLE
请问据你统计，目前哪套字体内的汉字数量最多

### ISSUE THREAD

**Issue by admin05** [NightFurySL2001/CJK-character-count#5]
请问据你统计，目前哪套字体内的汉字数量最多？谢谢

**Comment by NightFurySL2001** [comment]
本人并未针对一系列字体进行计数，毕竟网上已经有很多文章研究此问题。

这里列出一些比较常见的字体及其授权：
1. [天珩字库](http://cheonhyeong.com/Simplified/download.html)，私改非商用。其主要字体**天珩全字库(TH-Tshyn)**（宋体）是目前 Unicode 汉字覆盖量最大的字体，本软件的计数标准基本都可以满上（只要用对的字体计数）。汉字部分需要使用 TH-Tshyn-P0, P1, P2 联合显示。
2. [花园明朝 HanaMin](http://fonts.jp/hanazono/)（[OTF 版本](https://github.com/kawabata/glyphwiki-afdko)），开源（宋体）。在 [glyphwiki.org](glyphwiki.org) 上由群众一起制作字形生成的字体，覆盖至扩展 F 区。基本上依据日本标准写法。汉字部分需要使用 HanaMinA, HanaMinB, HanaMinC 联合显示。
3. [全字库](https://data.gov.tw/dataset/5961)，开源（宋体/楷体）。由台湾政府通过国家发展委员会依据 CNS11643 标准制作的字体，覆盖至扩展 E 区。基本上依据台湾教育部参考写法。汉字部分需要使用 TW-(Style)-98_1 和 TW-(Style)-Ext-B-98_1联合显示。
4. [BabelStone Han](https://www.babelstone.co.uk/Fonts/Han.html)，开源（宋体）。由英国人 Andrew West 制作，主要是制作 Unicode 内由 G 源（中国）提交的汉字，零散覆盖全部汉字区段。基本上依据中国国标写法。
5. [一点明体](https://github.com/ichitenfont/I.Ming)，开源（宋体）。由一点明体团队制作，主要是配合《传承字形部件校检表》制作的字体，零散覆盖全部汉字区段。基本上依据传承字形参考写法。

本问题无关计数软件，将会关闭本讨论。

**Comment by admin05** [comment]
非常感谢

**Comment by jianxiansiqi2025** [comment]
全宋体，收了19完漢字，如果不要印刷，查字學習的話是很方便的。

**Comment by admin05** [comment]
> 全宋体，收了19万个漢字，如果不要印刷，查字學習的話是很方便的。有部件檢索的html文件可供檢索。

谢谢您！
