### ISSUE TITLE
能否增加对GB18030-2005标准的检测呢？

### ISSUE THREAD

**Issue by MysteryMulberry** [NightFurySL2001/CJK-character-count#9]
这个工具真的很好用，不过若是能有对GB18030-2005字符集下的70000+字形的检测的话，就更好了。

**Comment by NightFurySL2001** [comment]
README 有相关内容：

> * [GB 18030](https://en.wikipedia.org/wiki/GB_18030)
> *Note: Mandatory section are counted only. According to GB 18030, mandatory section of a font is all CJK characters in the  Basic Multilingual Plane e.g. CJK Unified Ideographs and CJK Unified Ideographs Extension A.
> 注：只计算强制性标准部分。依据GB 18030，字体内强制需要支援的字符范围应该是基本多文种平面（BMP）内的所有汉字，即中日韩统一表意文字与中日韩统一表意文字扩展A区。*

另外，[目前的 OpenType 格式限制在 65,535 个字形（glyphs）](https://en.wikipedia.org/wiki/OpenType#:~:text=Accommodates%20up%20to%2065%2C536%20glyphs.)，即一个字体只能存放 65,535 个独特字形/字符，勉强只能收录 GB18030-2005 规定的中日韩统一表意文字扩展A和B区，不能放下中日韩统一表意文字的字符，更不可能再塞下西文和其他语系的字符，因此本软件没有提供 GB18030-2005 的计算功能。目前收录的是 GB18030-2000，对于字体设计较为合理。
